version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234qwer
    ports:
      - "4321:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    container_name: blog_delegator_server_c
    image: salahhaciakil/post_delegator_server
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PASSWORD=1234qwer
      - DB_USER=postgres
      - DB_DATABASE=postgres

  client:
    container_name: blog_delegator_client_c
    image: salahhaciakil/post_delegator_client
    build: ./frontend
    ports:
      - "3011:3011"
    depends_on:
      - server

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    # depends_on:
    #   - client
    volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #   - ./frontend/build:/usr/share/nginx/html
    # environment:
    #   - NGINX_HOST=foobar.com
    #   - NGINX_PORT=80

volumes:
  data:
